spring.application.name=pedidos360-backend-notificaciones
# Cambiamos el puerto para que no choque con el MS de Pedidos
server.port=8081

# Configuración de validación JWT con Azure AD (IDaaS)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/TU_TENANT_ID/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=TU_CLIENT_ID

# Configuración de RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Desactiva la base de datos para evitar errores de DataSource (paquetes nuevos de Spring Boot 4)
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.jdbc.autoconfigure.DataSourceInitializationAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration